Repository ghufran-adel/Mini-GameProject, pull requests merged in 2023-11, with the labels that each got.

#15 added back to the previous page button
  games-pages/HangMan/Hangman.css
  games-pages/HangMan/Hangman.html
  games-pages/HangMan/Hangman.js
  index.html
Labels: enhancement

#18 the game content is not displaying in the game container
  games-pages/Tic-Tac-Toe/Tic-Tac-Toe.css
  games-pages/Tic-Tac-Toe/Tic-Tac-Toe.html
Labels: bug

#21 Verifying Blackjack was pushed
  assets/img/AboutUs.png
  assets/img/kid-blackjack.png
  contact.css
  contact.html
  contact.js
  games-pages/Black-jack/Black-jack.css
  games-pages/Black-jack/Black-jack.html
  games-pages/Black-jack/Black-jack.js
  games-pages/Blackjack/Blackjack.css
  games-pages/Blackjack/Blackjack.html
  games-pages/Blackjack/Blackjack.js
Labels: enhancement

#20 comment
  games-pages/Tic-Tac-Toe/Tic-Tac-Toe.css
Labels: enhancement

#22 testing change to push
  games-pages/Blackjack/Blackjack.html
  games-pages/HangMan/Hangman.html
  games-pages/Rock-Paper-Scissors/Rock-paper-scissors.html
  games-pages/Tic-Tac-Toe/Tic-Tac-Toe.html
Labels: bug

#24 Change to make push request
  games-pages/Tic-Tac-Toe/Tic-Tac-Toe.html
Labels: bug

#25 modified the navigation file path
  games.html
  index.html
  leaderBorad.html
  login.html
Labels: enhancement

#26 we made the change to the back button both in Blackjack and Tic Tac Toe
  games-pages/Blackjack/Blackjack.css
  games-pages/Blackjack/Blackjack.html
  games-pages/Rock-Paper-Scissors/Rock-paper-scissors.js
  games-pages/Tic-Tac-Toe/Tic-Tac-Toe.css
  games-pages/Tic-Tac-Toe/Tic-Tac-Toe.html
Labels: enhancement

#27 New feature abdul
  CONTRIBUTING.md
  README.md
  index.html
  style.css
Labels: enhancement

#29 I added the fireFrames PDF
  Docs/WireFrames/Mini Game-WireFrames.pdf
Labels: documentation

#31 fix the responsive for mobile screen in the TicTacToe game page
  games-pages/Tic-Tac-Toe/Tic-Tac-Toe.css
Labels: enhancement

#33 Update README.md
  README.md
Labels: enhancement

#28 Blackjack theme, description, back button updated.
  assets/img/kid-blackjack-dark.png
  games-pages/Blackjack/Blackjack.css
  games-pages/Blackjack/Blackjack.html
  games-pages/Blackjack/Blackjack.js
Labels: enhancement

#34 Contact page updated for message and theme
  contact.css
  contact.html
  contact.js
Labels: enhancement

#35 Ghufran
  assets/img/GuessMyNumber.png
  assets/img/blackjack.jpg
  assets/img/hang-man.jpg
  assets/img/hang-man.png
  assets/img/play-again.png
  assets/img/rock-paper-scissors-game.avif
  assets/img/rock-paper-scissors-game.jpg
  games-pages/Rock-Paper-Scissors/Rock-paper-scissors.css
  games-pages/Rock-Paper-Scissors/Rock-paper-scissors.html
  games-pages/Rock-Paper-Scissors/Rock-paper-scissors.js
  index.html
  style.css
Labels: enhancement

#36 Update README.md
  README.md
Labels: enhancement

#38 Update README.md
  README.md
Labels: enhancement

#39 update the tic tac toe game comments
  games-pages/Tic-Tac-Toe/Tic-Tac-Toe.html
  games-pages/Tic-Tac-Toe/Tic-Tac-Toe.js
Labels: enhancement
